server:
  port: 8083

spring:
  application:
    name: reservas-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: hotel_reservas
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-container:9092}

reniec:
  api:
    url: ${RENIEC_API_URL:https://api.decolecta.com}
    key: ${RENIEC_API_KEY:sk_16611.snVv9jopvW7YQ8TL8jIPCYZ0GvrMMm4H}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hotelbonaventura: INFO
    org.hibernate.SQL: WARN
