server:
  port: 8082

spring:
  application:
    name: habitaciones-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: hotel_habitaciones
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: habitaciones-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hotelbonaventura.*"
        spring.json.value.default.type: com.hotelbonaventura.habitaciones.kafka.ReservaCompletadaEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.hotelbonaventura: INFO
    org.hibernate.SQL: WARN
